#!/usr/bin/env bash
set -euo pipefail
psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER}" <<-EOSQL
CREATE DATABASE feast;
CREATE DATABASE mlflow;
GRANT ALL PRIVILEGES ON DATABASE feast TO ${POSTGRES_USER};
GRANT ALL PRIVILEGES ON DATABASE mlflow TO ${POSTGRES_USER};
EOSQL
